Repository gdg-hongik-univ/cherrymap-untitled-server, pull requests merged in 2025-02, with the labels that each got.

#5 feat: 엔티티 클래스 개발
  src/main/java/com/untitled/cherrymap/domain/AlertMessage.java
  src/main/java/com/untitled/cherrymap/domain/Member.java
  src/main/java/com/untitled/cherrymap/domain/Route.java
  src/main/java/com/untitled/cherrymap/repository/AlertMessageRepository.java
  src/main/java/com/untitled/cherrymap/repository/MemberRepository.java
  src/main/java/com/untitled/cherrymap/repository/RouteRepository.java
Labels: enhancement

#6 카카오 로그인 API 연동
  .gitignore
  build.gradle
  src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
  src/main/java/com/untitled/cherrymap/controller/FrontendApiController.java
  src/main/java/com/untitled/cherrymap/controller/ThymeleafTestController.java
  src/main/java/com/untitled/cherrymap/domain/AlertMessage.java
  src/main/java/com/untitled/cherrymap/domain/Member.java
  src/main/java/com/untitled/cherrymap/domain/Route.java
  src/main/java/com/untitled/cherrymap/repository/AlertMessageRepository.java
  src/main/java/com/untitled/cherrymap/repository/MemberRepository.java
  src/main/java/com/untitled/cherrymap/repository/RouteRepository.java
  src/main/java/com/untitled/cherrymap/service/KakaoOAuth2MemberService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/templates/home.html
  src/main/resources/templates/index.html
  src/main/resources/templates/logout.html
Labels: enhancement

#12 Refactor and Fix: imports 복구 및 파일명 수정
  src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
  src/main/java/com/untitled/cherrymap/controller/MemberController.java
  src/main/java/com/untitled/cherrymap/service/KakaoOAuth2MemberService.java
Labels: bug, refactor

#13 Feat: 대중교통별 알림 메시지 반환 기능 구현
  src/main/java/com/untitled/cherrymap/controller/AlertMessageController.java
  src/main/java/com/untitled/cherrymap/domain/RouteRequest.java
  src/main/java/com/untitled/cherrymap/domain/Station.java
  src/main/java/com/untitled/cherrymap/service/AlertMessageService.java
  src/main/java/com/untitled/cherrymap/service/StationExtractorService.java
  src/main/java/com/untitled/cherrymap/service/TemplateService.java
Labels: enhancement, help wanted, question

#15 Chore: Swagger ui 이용한 API 문서화
  build.gradle
  src/main/java/com/untitled/cherrymap/config/OpenApiConfig.java
  src/main/java/com/untitled/cherrymap/controller/AlertMessageController.java
  src/main/java/com/untitled/cherrymap/domain/AlertMessage.java
  src/main/java/com/untitled/cherrymap/domain/Member.java
  src/main/java/com/untitled/cherrymap/domain/Route.java
  src/main/java/com/untitled/cherrymap/domain/RouteRequest.java
  src/main/java/com/untitled/cherrymap/domain/Station.java
  src/main/resources/application.properties
Labels: documentation

#16 Feat:Refactor:Fix: Member&Route 관련 기능 완성, 카카오 로그인 api 오류 수정
  build.gradle
  src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
  src/main/java/com/untitled/cherrymap/controller/MemberController.java
  src/main/java/com/untitled/cherrymap/controller/RouteController.java
  src/main/java/com/untitled/cherrymap/domain/Member.java
  src/main/java/com/untitled/cherrymap/domain/Route.java
  src/main/java/com/untitled/cherrymap/dto/RouteCreateRequest.java
  src/main/java/com/untitled/cherrymap/repository/RouteRepository.java
  src/main/java/com/untitled/cherrymap/service/KakaoOAuth2MemberService.java
  src/main/java/com/untitled/cherrymap/service/MemberService.java
  src/main/java/com/untitled/cherrymap/service/RouteService.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
Labels: bug, enhancement, refactor

#17 Fix: API 오류 시 카카오 인증 URL로 리다이렉션하는 문제 해결
  src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
  src/main/java/com/untitled/cherrymap/controller/ThymeleafTestController.java
  src/main/java/com/untitled/cherrymap/service/KakaoOAuth2MemberService.java
  src/main/resources/application.properties
  src/main/resources/templates/home.html
  src/main/resources/templates/index.html
Labels: bug

#18 Fix: 배포 환경 설정 및 배포 준비
  .gitignore
  build.gradle
  src/main/java/com/untitled/cherrymap/config/OpenApiConfig.java
  src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
  src/main/java/com/untitled/cherrymap/controller/AlertMessageController.java
  src/main/java/com/untitled/cherrymap/controller/MemberController.java
  src/main/java/com/untitled/cherrymap/controller/RouteController.java
  src/main/java/com/untitled/cherrymap/domain/AlertMessage.java
  src/main/java/com/untitled/cherrymap/domain/Member.java
  src/main/java/com/untitled/cherrymap/domain/Route.java
  src/main/java/com/untitled/cherrymap/domain/RouteRequest.java
  src/main/java/com/untitled/cherrymap/domain/Station.java
  src/main/java/com/untitled/cherrymap/dto/RouteCreateRequest.java
  src/main/java/com/untitled/cherrymap/repository/RouteRepository.java
  src/main/java/com/untitled/cherrymap/service/AlertMessageService.java
  src/main/java/com/untitled/cherrymap/service/KakaoOAuth2MemberService.java
  src/main/java/com/untitled/cherrymap/service/MemberService.java
  src/main/java/com/untitled/cherrymap/service/RouteService.java
  src/main/java/com/untitled/cherrymap/service/StationExtractorService.java
  src/main/java/com/untitled/cherrymap/service/TemplateService.java
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: bug, documentation, enhancement

#19 Fix: 병합 충돌 해결 중 누락된 파일 추가
  src/main/java/com/untitled/cherrymap/repository/AlertMessageRepository.java
  src/main/java/com/untitled/cherrymap/repository/MemberRepository.java
  src/main/resources/application-dev.properties
Labels: bug

#24 Fix: prod 설정 DB 연결 주소 수정
  src/main/resources/application-prod.properties
Labels: bug

#25 refactor: 테이블 생성하지 않기 위해 AlertMesaageRepository 삭제
  src/main/java/com/untitled/cherrymap/repository/AlertMessageRepository.java
Labels: bug

#31 Refactor: swagger ui example 수정 및 AlertMessageController 엔드포인트 수정
  src/main/java/com/untitled/cherrymap/controller/AlertMessageController.java
  src/main/java/com/untitled/cherrymap/domain/AlertMessage.java
  src/main/java/com/untitled/cherrymap/domain/RouteRequest.java
Labels: refactor

#32 Feat:Refactor: 예외 처리 패키지 추가 및 Route 엔티티 필드 mode 추가
  src/main/java/com/untitled/cherrymap/domain/Route.java
  src/main/java/com/untitled/cherrymap/dto/RouteCreateRequest.java
  src/main/java/com/untitled/cherrymap/exception/BadDataAccessException.java
  src/main/java/com/untitled/cherrymap/exception/BadRequestException.java
  src/main/java/com/untitled/cherrymap/exception/GlobalExceptionHandler.java
  src/main/java/com/untitled/cherrymap/message/ErrorMessage.java
  src/main/java/com/untitled/cherrymap/repository/RouteRepository.java
  src/main/java/com/untitled/cherrymap/service/KakaoOAuth2MemberService.java
  src/main/java/com/untitled/cherrymap/service/MemberService.java
  src/main/java/com/untitled/cherrymap/service/RouteService.java
Labels: bug, documentation, enhancement, refactor

#35 #34 merge (main <- dev)
  build.gradle
Labels: chore

#36 Fix: SecurityConfig CORS 이슈 해결
  src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
Labels: bug

#37 Fix: SecurityConfig CORS 이슈 해결
  src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
Labels: bug

#38 Chore: corsconfig에 localhost:5173 추가
  src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
Labels: chore

#39 Chore: corsconfig에 localhost:5173 추가
  src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
Labels: chore
